version: "2"
services:

  # Postgresql Database
  db:
    image: "skalera/postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "database"
